### ISSUE TITLE
I can't Access Woolf Platform on Anchor

### ISSUE THREAD

**Issue by Joshywoshys** [kiboschool/reports#9]
** Is your issue about the course content, or about the software platform?**
Yes
**Describe the bug**
I am having issues with accessing woolf, i tried it this morning and my results are not showing

** URL of the relevant page**
Enter the URL of the relevant page
https://github.com/kiboschool/reports/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**To Reproduce**
I logged to anchor
I clicked the woolf button
and it wouldnt load

**Do you have a screenshot of this issue that you can share with us?**
use the attach button
![full](https://github.com/kiboschool/reports/assets/85691466/cf63763c-c4f8-4a38-8bd0-052fe0ec44f2)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Joshy-A** [comment]
I have faced the same issues
...
